unsigned char httpHeaders[] = "HTTP/1.1 200 OK\r\n"
"Connection: keep-alive\r\n"
"Content-Type: text/html\r\n"
"Content-Length: ";

unsigned char xmlHeaders[] = "HTTP/1.1 200 OK\r\n"
"Connection: keep-alive\r\n"
"Content-Type: text/xml\r\n"
"Content-Length: ";

unsigned char page2[] =
"<html>\r\n"
"<body>\r\n"
"Access Point has been reconfigured"
"</body>\r\n"
"</html>";


const unsigned char page4[] =
"<!DOCTYPE html>\r\n"
"<html lang=\"en\"> \r\n"
"<head> \r\n"
"<title>Microchip EZConfig Application</title>\r\n"
"<script>\r\n"
"var xmlhttp;\r\n"
"function loadXMLDoc(url, cfunc, data)\r\n"
"{\r\n"
    "if (window.XMLHttpRequest)\r\n"
    "{\r\n"
        "xmlhttp = new XMLHttpRequest();\r\n"
        "xmlhttp.open((data==null)?\"GET\":\"POST\", url, true);\r\n"
        "xmlhttp.send(data);\r\n"
    "}\r\n"
    "else\r\n"
    "{\r\n"
        "xmlhttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n"
        "xmlhttp.open((data==null)?\"GET\":\"POST\", url, true);\r\n"
        "xmlhttp.send(data);\r\n"
    "}\r\n"
    "xmlhttp.onreadystatechange = cfunc;\r\n"
"}\r\n"
"function getXMLValue(xmlData, field, child) \r\n"
"{\r\n"
	"child = typeof(child) == \"undefined\" ? 0 : child;\r\n"

	"try {\r\n"
		"if(xmlData.getElementsByTagName(field)[child].firstChild.nodeValue)\r\n"
			"return xmlData.getElementsByTagName(field)[child].firstChild.nodeValue;\r\n"
		"else\r\n"
			"return null;\r\n"
	"} catch(err) { return null; }\r\n"
"}\r\n"
"function switchNetwork(id)\r\n"
"{\r\n"
	"var name = id;\r\n"
	"if (name == \"\")\r\n"
	"{\r\n"
		"alert('SSID cannot be left blank!');\r\n"
		"return;\r\n"
	"}\r\n"
	"document.getElementById(\"SSID2\").value = name;\r\n"
"}\r\n"

"function deleteWiFiScanTable()\r\n"
"{\r\n"
    "var table = document.getElementById('scanTable').getElementsByTagName('tbody')[0];\r\n"
    "var rows = table.rows;\r\n"

    "while (rows.length - 1)\r\n"
        "table.deleteRow(rows.length - 1);\r\n"
"}\r\n"
"function addScanRow(ssid)\r\n"
"{\r\n"
	"var tbody = document.getElementById('scanTable').getElementsByTagName(\"tbody\")[0];\r\n"
	"var row = document.createElement(\"tr\");\r\n"

	"row.setAttribute('id', ssid);\r\n"
	"row.setAttribute('onmouseover', \"this.style.cursor='pointer'\");\r\n"
        "row.setAttribute('onclick', 'switchNetwork(id);');\r\n"
	"var data1 = document.createElement(\"td\");\r\n"
	"data1.setAttribute('style', 'width:10em');\r\n"
	"data1.appendChild(document.createTextNode(ssid));\r\n"

	"row.appendChild(data1);\r\n"
	"tbody.appendChild(row);\r\n"
"}\r\n"
"function scanWiFiNetwork()\r\n"
"{\r\n"
    "deleteWiFiScanTable();\r\n"
    "loadXMLDoc('scanresults.xml?scan=1',function()\r\n"
    "{\r\n"
        "if (xmlhttp.readyState==4 && xmlhttp.status==200)\r\n"
        "{\r\n"
            "var i,x;\r\n"
             "xmlData = xmlhttp.responseXML;\r\n"
             "x = xmlhttp.responseXML.documentElement.getElementsByTagName(\"bss\");\r\n"
             "txt=\"\";\r\n"
             "for(i=0; i < x.length; i++)\r\n"
             "{\r\n"
                     "addScanRow( getXMLValue(xmlData, 'ssid', i) );\r\n"
             "}\r\n"
        "}\r\n"
   "});\r\n"
"}\r\n"
"</script>\r\n"
"<style>\r\n"
"body { \r\n"
"background-color: #312e1d;\r\n"
"font-family: tahoma, sans-serif;\r\n"
"}\r\n"
"#content {\r\n"
"margin: 20px auto;\r\n"
"width: 600px;\r\n"
"background-color: #f8f8f8;\r\n"
"padding: 20px 10px;\r\n"
"border: solid 3px red;\r\n"
"}\r\n"

"h1 {\r\n"
"font-size: 120%;\r\n"
"}\r\n"
"input[type=text] {\r\n"
"width: 400px;\r\n"
"}\r\n"
"tr.label {\r\n"
"vertical-align: top;\r\n"
"}\r\n"
"#menu {\r\n"
	"float: left;\r\n"
	"width: 150px;\r\n"
	"padding-right: 5px;\r\n"
"}\r\n"
"#menu a {\r\n"
	"width: 145px;\r\n"
	"display: block;\r\n"
	"background: #c00;\r\n"
	"color: white;\r\n"
	"padding: 5px;\r\n"
	"font-weight: bold;\r\n"
	"border-bottom: 2px solid #fff;\r\n"
	"text-decoration: none;\r\n"
"}\r\n"
"#menu a:hover {\r\n"
	"background: #d33;\r\n"
"}\r\n"
"</style>\r\n"
"</head>\r\n"
"<body>\r\n"
"<div id=\"content\">\r\n"
"<h1 style=\"text-align:center\"> Device Configuration Form </h1>\r\n"
"<div id=\"menu\">\r\n"
    "<a href=\"/index.htm\">Configure</a>\r\n"
    "<a href=\"/advance.htm\">Advanced Features</a>\r\n"
"</div>\r\n"
"<form method=\"post\" action=\"http://5.16.71.1:2000\">\r\n"
"<table>\r\n"
"<tr>\r\n"
"<td height=\"20\"></td>\r\n"
"</tr>\r\n"
"<tr>\r\n"
"<td class=\"label\">SSID</td>\r\n"
"<td class=\"form\"><input name=\"SSID\" type=\"text\" id=\"SSID2\" /></td>\r\n"
"</tr>\r\n"
"<tr>\r\n"
"<td class=\"label\">Network Password</td>\r\n"
"<td class=\"form\"><input name=\"password\" type=\"text\" /></td>\r\n"
"</tr>\r\n"
"<tr>\r\n"
"<td class=\"label\">Channel</td>\r\n"
"<td class=\"form\">\r\n"
"<select name=\"Channel\">\r\n"
"<option value=\"\">-- Select channel --</option>\r\n"
"<option value=\"0\">Search On All Channels</option>\r\n"
"<option value=\"1\">Channel 1</option>\r\n"
"<option value=\"2\">Channel 2</option>\r\n"
"<option value=\"3\">Channel 3</option>\r\n"
"<option value=\"4\">Channel 4</option>\r\n"
"<option value=\"5\">Channel 5</option>\r\n"
"<option value=\"6\">Channel 6</option>\r\n"
"<option value=\"7\">Channel 7</option>\r\n"
"<option value=\"8\">Channel 8</option>\r\n"
"<option value=\"9\">Channel 9</option>\r\n"
"<option value=\"10\">Channel 10</option>\r\n"
"<option value=\"11\">Channel 11</option>\r\n"
"</select>\r\n"
"</td>"
"</tr>"
"<tr>\r\n"
"<td class=\"label\">Auto-Join</td>\r\n"
"<td class=\"form\">\r\n"
"Enable <input type=\"radio\" name=\"AutoJoin\" value=\"Yes\"  /> &nbsp;\r\n"
"Disable <input type=\"radio\" name=\"AutoJoin\" value=\"No\" checked/> &nbsp;\r\n"
"</td>\r\n"
"</tr>\r\n"
"<tr>\r\n"
"<td height=\"20\"></td>\r\n"
"</tr>\r\n"
"<tr>\r\n"
"<td></td>\r\n"
"<td><input type=\"submit\" name=\"submit\" value=\" Enter \" /></td>\r\n"
"</tr>\r\n"
"<tr>\r\n"
"<td height=\"40\"></td>\r\n"
"</tr>\r\n"
"</table>"
        "<table id=\"scanTable\">\r\n"
    	"<tbody>\r\n"
    		"<tr>\r\n"
    			"<td colspan=\"4\">\r\n"
    				"<input id=\"rescan\" type=\"button\" style=\"width:18em\" \r\n"
    				  "value=\"View Available Wireless Networks...\" onclick=\"scanWiFiNetwork();\"></input>\r\n"
    			"</td>\r\n"
    		"</tr>\r\n"
    	"</tbody>\r\n"
        "</table>\r\n"
"</form>\r\n"
"</div>\r\n"
"</body>\r\n"
"</html>";


const unsigned char advanced1[] =
"<!DOCTYPE html>\r\n"
"<html lang=\"en\"> \r\n"
"<head> \r\n"
"<title>Microchip EZConfig Application</title>\r\n"

"<style>\r\n"
"body { \r\n"
"background-color: #312e1d;\r\n"
"font-family: tahoma, sans-serif;\r\n"
"}\r\n"
"#content {\r\n"
"margin: 20px auto;\r\n"
"width: 600px;\r\n"
"background-color: #f8f8f8;\r\n"
"padding: 20px 10px;\r\n"
"border: solid 3px red;\r\n"
"}\r\n"

"h1 {\r\n"
"font-size: 120%;\r\n"
"}\r\n"
"input[type=text] {\r\n"
"width: 400px;\r\n"
"}\r\n"
"tr.label {\r\n"
"vertical-align: top;\r\n"
"}\r\n"
"#menu {\r\n"
	"float: left;\r\n"
	"width: 150px;\r\n"
	"padding-right: 5px;\r\n"
"}\r\n"
"#menu a {\r\n"
	"width: 145px;\r\n"
	"display: block;\r\n"
	"background: #c00;\r\n"
	"color: white;\r\n"
	"padding: 5px;\r\n"
	"font-weight: bold;\r\n"
	"border-bottom: 2px solid #fff;\r\n"
	"text-decoration: none;\r\n"
"}\r\n"
"#menu a:hover {\r\n"
	"background: #d33;\r\n"
"}\r\n"
"</style>\r\n"
"</head>\r\n"
"<body>\r\n"
"<div id=\"content\">\r\n"
"<h1 style=\"text-align:center\"> Module Advanced Features </h1>\r\n"
"<div id=\"menu\">\r\n"
    "<a href=\"/index.htm\">Configure</a>\r\n"
    "<a href=\"/advance.htm\">Advanced Features</a>\r\n"
"</div>\r\n"
"<form>\r\n"
    "<table>\r\n"
        "<tr>\r\n"
        "<td height=\"20\"></td>\r\n"
        "</tr>\r\n"
        "<tr>\r\n"
            "<td class=\"label\">Mac Address:</td>\r\n"
            "<td class=\"form\"><input name=\"MAC\" type=\"text\" value=\"00:06:66:81:06:03\" disabled /></td>\r\n"
        "</tr>\r\n"

        "<tr>\r\n"
            "<td class=\"label\">Network SSID:</td>\r\n"
            "<td class=\"form\"><input name=\"ssid3\" type=\"text\" value=\"mttSoftAP_03_06\" disabled /></td>\r\n"
        "</tr>\r\n"

        "<tr>\r\n"
            "<td class=\"label\">Firmware Version:</td>\r\n"
            "<td class=\"form\"><input name=\"frmversion\" type=\"text\" value=\"2.45\" disabled /></td>\r\n"
        "</tr>\r\n"

        "<tr>\r\n"
            "<td height=\"20\"></td>\r\n"
        "</tr>\r\n"

    "</table>\r\n"
  "</form>\r\n"
"</div>\r\n"
"</body>\r\n"
"</html>";


const unsigned char advanced_part1[] =
"<!DOCTYPE html>\r\n"
"<html lang=\"en\"> \r\n"
"<head> \r\n"
"<title>Microchip EZConfig Application</title>\r\n"

"<style>\r\n"
"body { \r\n"
"background-color: #312e1d;\r\n"
"font-family: tahoma, sans-serif;\r\n"
"}\r\n"
"#content {\r\n"
"margin: 20px auto;\r\n"
"width: 600px;\r\n"
"background-color: #f8f8f8;\r\n"
"padding: 20px 10px;\r\n"
"border: solid 3px red;\r\n"
"}\r\n"

"h1 {\r\n"
"font-size: 120%;\r\n"
"}\r\n"
"input[type=text] {\r\n"
"width: 400px;\r\n"
"}\r\n"
"tr.label {\r\n"
"vertical-align: top;\r\n"
"}\r\n"
"#menu {\r\n"
	"float: left;\r\n"
	"width: 150px;\r\n"
	"padding-right: 5px;\r\n"
"}\r\n"
"#menu a {\r\n"
	"width: 145px;\r\n"
	"display: block;\r\n"
	"background: #c00;\r\n"
	"color: white;\r\n"
	"padding: 5px;\r\n"
	"font-weight: bold;\r\n"
	"border-bottom: 2px solid #fff;\r\n"
	"text-decoration: none;\r\n"
"}\r\n"
"#menu a:hover {\r\n"
	"background: #d33;\r\n"
"}\r\n"
"</style>\r\n"
"</head>\r\n"
"<body>\r\n"
"<div id=\"content\">\r\n"
"<h1 style=\"text-align:center\"> Module Advanced Features </h1>\r\n"
"<div id=\"menu\">\r\n"
    "<a href=\"/index.htm\">Configure</a>\r\n"
    "<a href=\"/advance.htm\">Advanced Features</a>\r\n"
"</div>\r\n"
"<form>\r\n"
    "<table>\r\n"
        "<tr>\r\n"
        "<td height=\"20\"></td>\r\n"
        "</tr>\r\n"
        "<tr>\r\n"
            "<td class=\"label\">Mac Address:</td>\r\n";


const unsigned char advanced_part2[] =
        "</tr>\r\n"
        "<tr>\r\n"
        "<td class=\"label\">Network SSID:</td>\r\n";
         

const unsigned char advanced_part3[] =
        "</tr>\r\n"
        "<tr>\r\n"
            "<td class=\"label\">Firmware Version:</td>\r\n"
            "<td class=\"form\"><input name=\"frmversion\" type=\"text\" value=\"2.45\" disabled /></td>\r\n"
         "</tr>\r\n"
        "<tr>\r\n"
            "<td height=\"20\"></td>\r\n"
        "</tr>\r\n"
    "</table>\r\n"
  "</form>\r\n"
"</div>\r\n"
"</body>\r\n"
"</html>";

